### ISSUE TITLE
API is broken

### ISSUE THREAD

**Issue by addreas** [datasektionen/dfunkt#8]
Seems like the type column is missing in the database. 

``````
Executing (default): SELECT "id", "title", "description", "email", "type" FROM "Roles" AS "Role" WHERE "Role"."title" = 'jsimo' LIMIT 1;
2016-08-31T09:04:08.035970852Z app[web.1]: Unhandled rejection SequelizeDatabaseError: column "type" does not exist
2016-08-31T09:04:08.035986126Z app[web.1]:     at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
2016-08-31T09:04:08.035992536Z app[web.1]:     at null.<anonymous> (/app/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
2016-08-31T09:04:08.035998453Z app[web.1]:     at emitOne (events.js:90:13)
2016-08-31T09:04:08.036003241Z app[web.1]:     at emit (events.js:182:7)
2016-08-31T09:04:08.036007795Z app[web.1]:     at Query.handleError (/app/node_modules/pg/lib/query.js:108:8)
2016-08-31T09:04:08.036012382Z app[web.1]:     at null.<anonymous> (/app/node_modules/pg/lib/client.js:171:26)
2016-08-31T09:04:08.036017130Z app[web.1]:     at emitOne (events.js:90:13)
2016-08-31T09:04:08.036025761Z app[web.1]:     at emit (events.js:182:7)
2016-08-31T09:04:08.036030348Z app[web.1]:     at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:109:12)
2016-08-31T09:04:08.036035268Z app[web.1]:     at emitOne (events.js:90:13)
2016-08-31T09:04:08.036039657Z app[web.1]:     at Socket.emit (events.js:182:7)
2016-08-31T09:04:08.036044063Z app[web.1]:     at readableAddChunk (_stream_readable.js:153:18)
2016-08-31T09:04:08.036048455Z app[web.1]:     at Socket.Readable.push (_stream_readable.js:111:10)
2016-08-31T09:04:08.036052804Z app[web.1]:     at TCP.onread (net.js:534:20)
t```
``````

**Comment by JSimo** [comment]
Ser felet, role har tappat en attribut den hade tidigare under utvecklingen. Tar och kollar på det nu.
